'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Panta_Valve.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallCheckValveFlanged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallCheckValveFlanged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallCheckValveGluedPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallCheckValveGluedPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallCheckValveGluedTrueUnionPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallCheckValveGluedTrueUnionPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallCheckValveGluedUnionPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallCheckValveGluedUnionPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallValveButweldSSautomated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallValveButweldSSautomated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallValveFlangedSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallValveFlangedSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallValveFlangedSSautomated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallValveFlangedSSautomated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallValveGluedPVCautomated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallValveGluedPVCautomated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BallValveThreadedSSautomated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallValveThreadedSSautomated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyAutomatedSanitary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyAutomatedSanitary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyManualLUG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyManualLUG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyManualSanitary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyManualSanitary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyManualWafer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyManualWafer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyManualWheel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyManualWheel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyPneumaticLUG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyPneumaticLUG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButterflyPneumaticWafer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButterflyPneumaticWafer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtWeldBallValve3pieces() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtWeldBallValve3pieces", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtWeldBallValve3pieces1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtWeldBallValve3pieces1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CheckValveLiftRVS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckValveLiftRVS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveAutomatedWeldedSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveAutomatedWeldedSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveFlangedAutomatedPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveFlangedAutomatedPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveFlangedCS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveFlangedCS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveFlangedManualPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveFlangedManualPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveGluedAutomatedPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveGluedAutomatedPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveGluedManualPVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveGluedManualPVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiafragmValveManualWeldedSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiafragmValveManualWeldedSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiskCheckValve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiskCheckValve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DualPlateCheckValve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DualPlateCheckValve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlangedBallValvePVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlangedBallValvePVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GateValveFlangedCS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GateValveFlangedCS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GateValveFlangedSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GateValveFlangedSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GateValveKnifeWafer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GateValveKnifeWafer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GateValveThreaded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GateValveThreaded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlobeValveFlangedCS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlobeValveFlangedCS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlobeValveFlangedSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlobeValveFlangedSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlobeValveThreaded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlobeValveThreaded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlobeValveWelded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlobeValveWelded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PB_SplashValve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PB-SplashValve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SocketGluedBallValvePVC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SocketGluedBallValvePVC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SocketWeldBallValvePP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SocketWeldBallValvePP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrainerFLanged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrainerFLanged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrainerGlued() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrainerGlued", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StrainerThreaded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrainerThreaded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwingCheckValve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwingCheckValve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThreadedBallValve2piecesSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreadedBallValve2piecesSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThreadedBallValve3piecesSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreadedBallValve3piecesSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
